#!/bin/bash

start-test() {
    local ip=$(cat $TEST_DIR/databases/*/metadata/ip)
    local port=$(cat $TEST_DIR/databases/*/metadata/port)
    local pass=$(cat $TEST_DIR/databases/*/metadata/password)
    local test_image=mcr.microsoft.com/mssql/server:2019-latest

    sleep 30

    KINE_IMAGE=$IMAGE KINE_ENDPOINT="sqlserver://ismilletest.database.windows.net:1433?database=kine&fedauth=ActiveDirectoryDefault" provision-kine
    local kine_url=$(cat $TEST_DIR/kine/*/metadata/url)
    K3S_DATASTORE_ENDPOINT=$kine_url provision-cluster
}

export -f start-test

VERSION_LIST="\
    sqlserver 2022-latest"

while read ENGINE VERSION; do
    LABEL=$ENGINE-$VERSION DB_PASSWORD_ENV=MSSQL_SA_PASSWORD DB_IMAGE=mcr.microsoft.com/mssql/server:$VERSION run-test
done <<< $VERSION_LIST